name: nof1_models
description: Nof1 Models for app and study designer
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  parse_server_sdk:
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: release/1.0.27

dev_dependencies:
  build_runner:
  effective_dart:
  flutter_test:
    sdk: flutter
  json_serializable:
