version: '3.8'
name: 'studyu_proxy'

networks:
  default:
    name: studyu_network
    external: true

services:
  nginx:
    container_name: studyu-proxy
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "${STUDYU_APP_PORT}:${STUDYU_APP_SSL_INTERNAL_PORT:-8080}"
      - "${STUDYU_DESIGNER_PORT}:${STUDYU_DESIGNER_SSL_INTERNAL_PORT:-8081}"
      - "${STUDYU_SUPABASE_PORT}:${STUDYU_SUPABASE_SSL_INTERNAL_PORT:-8082}"
    volumes:
      - ../nginx/proxy:/etc/nginx/templates:ro
      - ../nginx/certs:/etc/ssl/private:ro
    env_file:
      - .env
