version: '3'
services:
  designer2-selfhost:
    build:
      context: ../..
      dockerfile: ../Dockerfile
      args:
        FLUTTER_APP_FOLDER: designer_v2
        ENV: selfhost
    ports:
      - 8082:80
    networks:
      - studyu-net
    env_file:
      - ../../flutter_common/lib/envs/.env.selfhost
networks:
  studyu-net:
    name: studyu_network
