version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: ../Dockerfile
      args:
        FLUTTER_APP_FOLDER: app
        ENV: staging
    ports:
      - 8080:80
    env_file:
      - ../../flutter_common/lib/envs/.env.staging
