version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    open-pull-requests-limit: 10
    directory: "core/"
    schedule:
      interval: "daily"
    labels:
      - "core"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 10
    directory: "flutter_common/"
    schedule:
      interval: "daily"
    labels:
      - "flutter_common"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 10
    directory: "app/"
    schedule:
      interval: "daily"
    labels:
      - "app"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 10
    directory: "designer/"
    schedule:
      interval: "daily"
    labels:
      - "designer"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 10
    directory: "notebook_uploader/"
    schedule:
      interval: "daily"
    labels:
      - "notebook_uploader"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 10
    directory: "repo_generator/"
    schedule:
      interval: "daily"
    labels:
      - "repo_generator"
      - "dependencies"