version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    open-pull-requests-limit: 20
    directory: "core/"
    schedule:
      interval: "daily"
    labels:
      - "core"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 20
    directory: "flutter_common/"
    schedule:
      interval: "daily"
    labels:
      - "flutter_common"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 20
    directory: "app/"
    schedule:
      interval: "daily"
    labels:
      - "app"
      - "dependencies"
  - package-ecosystem: "pub"
    open-pull-requests-limit: 20
    directory: "designer_v2/"
    schedule:
      interval: "daily"
    labels:
      - "designer_v2"
      - "dependencies"
