'core':
  - changed-files:
      - any-glob-to-any-file: 'core/**/*'
'designer_v2':
  - changed-files:
      - any-glob-to-any-file: 'designer_v2/**/*'
'app':
  - changed-files:
      - any-glob-to-any-file: 'app/**/*'
'flutter_common':
  - changed-files:
      - any-glob-to-any-file: 'flutter_common/**/*'
'dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - '**/pubspec.yaml'
          - '**/pubspec.lock'
'documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '**/*.md'
