# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

VALIDATE_ALL_CODEBASE: true

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
 - ACTION_ACTIONLINT
# - DART_DARTANALYZER
 - MARKDOWN_MARKDOWNLINT
 - MARKDOWN_MARKDOWN_TABLE_FORMATTER
 - MARKDOWN_MARKDOWN_LINK_CHECK
 - DOCKERFILE_DOCKERFILELINT
 - REPOSITORY_GIT_DIFF
 # - REPOSITORY_GITLEAKS
 - BASH_SHELLCHECK
 - JSON_JSONLINT
 - JSON_ESLINT_PLUGIN_JSONC
# - SQL_SQLFLUFF
 - ENV_DOTENV_LINTER

DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
 - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

EXCLUDED_DIRECTORIES:
  - .git
  - android
  - ios
  - macos
  - windows
  - linux
  - web

FILTER_REGEX_EXCLUDE: (.*\.g\.dart|.*\/CHANGELOG.md|docs/database/.*|docs/uml/.*|studyu|docker\/supabase\/volumes\/.*|.*\/fastlane\/README.md)

# Linter specific settings

BASH_SHELLCHECK_ARGUMENTS: -ax -S style --shell=bash
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .markdown_link_check.yml
ACTION_ACTIONLINT_FILTER_REGEX_EXCLUDE: (.*\/.github\/workflows\/init-workspace\/action\.yml)
# SQL_SQLFLUFF_CONFIG_FILE: .sqlfluff
