version: '3'
services:
  designer2:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: designer_v2
        ENV: staging
    ports:
      - 80:80
      - 443:443
    env_file:
      - flutter_common/lib/envs/.env.staging
