version: '3'
services:
  app:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: app
        PARSE_APP_ID: nof1-local
        PARSE_MASTER_KEY: nof1-local
        PARSE_SERVER_URL: http://localhost:1337/parse
    ports:
      - 8081:80
    depends_on:
      - parse
