version: '3'
services:
  study_designer:
    environment:
      - FLUTTER_PARSE_APP_ID=nof1-local
      - FLUTTER_PARSE_SERVER_URL=http://localhost:1337/parse
      - FLUTTER_PARSE_DEBUG=true
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: study_designer
    ports:
      - 8080:80
