version: '3'
services:
  designer:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: designer_v2
    ports:
      - 8082:80
    env_file:
      - flutter_common/lib/envs/.env.staging
