version: '3'
services:
  app:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: app
    ports:
      - 8080:80
    env_file:
      - flutter_common/lib/envs/.env.staging
  designer:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: designer
    ports:
      - 8081:80
    env_file:
      - flutter_common/lib/envs/.env.staging
  designer2:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: designer_v2
    ports:
      - 8082:80
    env_file:
      - flutter_common/lib/envs/.env.staging