name: studyu-packages

repository: https://github.com/hpi-studyu/studyu

packages:
  - app
  - designer_v2
  - core
  - flutter_common

command:
  clean:
    hooks:
      # Clean things very deeply, can be used to establish "pristine checkout" status
      pre: >
        git clean -x -d -f -q || true
      # Additional cleanup lifecycle script, executed when `melos clean` is ran.
      post: >
        melos exec --flutter --concurrency=3 -- "flutter clean"

scripts:
  analyze:
    # Exit with success if markdownlint is not installed so it's not a requirement
    # (stream redirection has to be POSIX compliant for GH runners)
    run: |
      melos exec -c 6 -- \
        "flutter analyze --fatal-infos ."
      if markdownlint -V >/dev/null 2>&1; then
        printf "\n\033[1mLinting Markdown files ...\033[0;31m\n\n"
        markdownlint './**/*.md' --ignore './**/CHANGELOG.md' --ignore './**/ios/**' --ignore './**/android/**' \
          && printf "\033[0;32mSuccess!\033[0m\n"
      else
        printf "\n\033[1mCannot lint markdown files since markdownlint is not installed.\033[0m\n\n"
      fi
    description: |
      Run `dart analyze` in all packages, and, if `markdownlint` is installed, lint Markdown files.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      melos exec -c 6 -- \
        "dart format -l 120 ."
      markdownlint './**/*.md' --ignore './**/CHANGELOG.md' --ignore './**/ios/**' --ignore './**/android/**' --fix
    description: Format all code & Markdown files

  fix:
    run: |
      melos exec -c 6 -- \
        "dart fix --apply"
    description: Fix auto-fixable lint errors

  format:ci:
    run: |
      melos exec -c 6 -- \
        "find . -type f -name '*.dart' ! -name '*.g.dart' ! -path '**/.dart_tool/**' | tr '\n' ' ' | xargs dart format -l 120 --set-exit-if-changed"
    description: Format all code without generated files

  outdated:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart pub outdated"
    description: Check all outdated dependencies

  upgrade:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart pub upgrade" && melos bootstrap
    description: Check all outdated dependencies

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dir-exists: test

  generate:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Generate files with build_runner
    packageFilters:
      scope: studyu_core

  dev:designer:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 3001 --dart-define=STUDYU_ENV=.env.selfhost"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs designer in Chrome on port 3001 with selfhost env for local development

  dev:app:
    run: |
      melos exec -c 1 -- \
        "flutter run --dart-define=STUDYU_ENV=.env.selfhost"
    packageFilters:
      scope: studyu_app
    description: Runs app with selfhost env for local development

  build:android:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build apk --no-tree-shake-icons --multidex"
    description: Build app for Android.
    packageFilters:
      dir-exists: android

  build:ios:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build ipa --no-codesign --no-tree-shake-icons"
    description: Build app for iOS.
    packageFilters:
      dir-exists: ios

  build:web:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    packageFilters:
      scope: [studyu_app, studyu_designer_v2]
      dir-exists: web

  build:web:app:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    packageFilters:
      scope: studyu_app

  build:web:designer:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build designer for Web.
    packageFilters:
      scope: studyu_designer

  build:web:designer_v2:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build designer_v2 for Web.
    packageFilters:
      scope: studyu_designer_v2

  # Staging Env

  build:web:staging:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.staging"
    description: Build web staging.
    packageFilters:
      scope: [studyu_app, studyu_designer_v2]
      dir-exists: web

  build:web:app:staging:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.staging"
    description: Build web app staging.
    packageFilters:
      scope: studyu_app
      dir-exists: web

  build:web:designer:staging:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.staging"
    description: Build designer app staging.
    packageFilters:
      scope: studyu_designer
      dir-exists: web

  build:web:designer_v2:staging:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.staging"
    description: Build designer_v2 staging.
    packageFilters:
      scope: studyu_designer_v2
      dir-exists: web

  # Selfhost Env

  build:web:app:selfhost:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.selfhost"
    description: Build app for Docker and self-hosted Supabase instance.
    packageFilters:
      scope: studyu_app

  build:web:designer:selfhost:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.selfhost"
    description: Build designer for Docker and self-hosted Supabase instance.
    packageFilters:
      scope: studyu_designer

  build:web:designer_v2:selfhost:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.selfhost"
    description: Build designer_v2 for Docker and self-hosted Supabase instance.
    packageFilters:
      scope: studyu_designer_v2

  # Used to test Designer "Try out study" feature, where the designer opens the App using the user auth token from designer
  app:web:local:
    run: |
      melos exec -c 1 -- \
        "flutter run lib/main.dart -d chrome --web-port 3001 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_app
    description: Runs app in chrome on port 3001 with local env

  designer:web:local:
    run: |
      melos exec -c 1 -- \
        "flutter run lib/main.dart -d chrome --web-port 3000 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_designer
    description: Runs designer in chrome on port 3000 with local env
