name: studyu

repository: https://github.com/hpi-studyu/studyu

packages:
  - app
  - designer_v2
  - core
  - flutter_common

scripts:
  fix:
    run: |
      melos exec -c 6 -- \
        "dart fix --apply"
    description: Fix auto-fixable lint errors

  outdated:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart pub outdated"
    description: Check all outdated dependencies

  upgrade:
    run: |
      dart pub upgrade
      melos exec -c 6 --fail-fast -- \
        "dart pub upgrade" && melos bootstrap
    description: Check all outdated dependencies

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists: test

  generate:
    run: |
      melos exec -c 1 --fail-fast -- \
        "dart run build_runner build --delete-conflicting-outputs"
    description: Generate files with build_runner
    packageFilters:
      scope:
        - 'studyu_core'
        - 'studyu_designer_v2'

  reset:
    run: |
      git clean -x -d -f -q || true
      melos clean
      melos exec --flutter --concurrency=1 -- "flutter clean"
      melos bootstrap
    description: Reset the workspace to a pristine checkout status.

  app:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8080"
    packageFilters:
      scope: studyu_app
    description: Runs StudyU App with default environment

  designer_v2:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8081"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs StudyU Designer with default environment

  dev:app:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8080 --dart-define=STUDYU_ENV=.env.dev"
    packageFilters:
      scope: studyu_app
    description: Runs StudyU App with the development environment

  dev:designer_v2:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8081 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs StudyU Designer with the development environment

  local:app:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8080 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_app
    description: Runs StudyU App with local environment

  local:designer_v2:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8081 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs StudyU Designer with local environment

  build:android:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build apk"
    description: Build app for Android.
    packageFilters:
      dirExists: android

  build:ios:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build ipa --no-codesign"
    description: Build app for iOS.
    packageFilters:
      dirExists: ios

  build:web:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web"
    description: Build app for Web.
    packageFilters:
      scope: [ studyu_app, studyu_designer_v2 ]
      dirExists: web

  build:web:app:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web"
    description: Build app for Web.
    packageFilters:
      scope: studyu_app

  build:web:designer_v2:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web"
    description: Build designer_v2 for Web.
    packageFilters:
      scope: studyu_designer_v2

  build:web:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --dart-define=STUDYU_ENV=.env.dev"
    description: Build web dev.
    packageFilters:
      scope: [ studyu_app, studyu_designer_v2 ]
      dirExists: web

  build:web:app:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --dart-define=STUDYU_ENV=.env.dev"
    description: Build web app dev.
    packageFilters:
      scope: studyu_app
      dirExists: web

  build:web:designer_v2:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --dart-define=STUDYU_ENV=.env.dev"
    description: Build web designer_v2 dev.
    packageFilters:
      scope: studyu_designer_v2
      dirExists: web
