name: studyu-packages

repository: https://github.com/hpi-studyu/studyu

packages:
  - app
  - designer_v2
  - core
  - flutter_common

command:
  clean:
    hooks:
      # Clean things very deeply, can be used to establish "pristine checkout" status
      pre: >
        git clean -x -d -f -q || true
      # Additional cleanup lifecycle script, executed when `melos clean` is ran.
      post: >
        melos exec --flutter --concurrency=3 -- "flutter clean"

scripts:
  analyze:
    run: |
      melos exec -c 6 -- \
        "flutter analyze --fatal-infos ."
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  fix:
    run: |
      melos exec -c 6 -- \
        "dart fix --apply"
    description: Fix auto-fixable lint errors

  # todo exclude *.g.dart files in a platform agnostic way
  # dart format sadly does not support this yet: https://github.com/dart-lang/dart_style/issues/864
  format:
    run: |
      melos exec -c 6 -- \
        "dart format -l 120 ."
        markdownlint --ignore-path '.meta/.markdownlintignore' --config '.meta/.mdlrc' './**/*.md' --fix
    description: Format all code and markdown files

  format:ci:
    run: |
      melos exec -c 6 -- \
        "find . -type f -name '*.dart' ! -name '*.g.dart' ! -path '**/.dart_tool/**' | tr '\n' ' ' | xargs dart format -l 120 --set-exit-if-changed"
    description: Format all code without generated files

  outdated:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart pub outdated"
    description: Check all outdated dependencies

  upgrade:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart pub upgrade" && melos bootstrap
    description: Check all outdated dependencies

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dir-exists: test

  generate:
    run: |
      melos exec -c 1 --fail-fast -- \
        "dart run build_runner build --delete-conflicting-outputs"
    description: Generate files with build_runner
    packageFilters:
      scope: studyu_core

  dev:designer:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 3001 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs designer in Chrome on port 3001 with local env for local development

  dev:app:
    run: |
      melos exec -c 1 -- \
        "flutter run --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_app
    description: Runs app with local env for local development

  build:android:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build apk --no-tree-shake-icons --multidex"
    description: Build app for Android.
    packageFilters:
      dir-exists: android

  build:ios:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build ipa --no-codesign --no-tree-shake-icons"
    description: Build app for iOS.
    packageFilters:
      dir-exists: ios

  build:web:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    packageFilters:
      scope: [studyu_app, studyu_designer_v2]
      dir-exists: web

  build:web:app:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    packageFilters:
      scope: studyu_app

  build:web:designer_v2:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons"
    description: Build designer_v2 for Web.
    packageFilters:
      scope: studyu_designer_v2

  build:web:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.dev"
    description: Build web dev.
    packageFilters:
      scope: [studyu_app, studyu_designer_v2]
      dir-exists: web

  build:web:app:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.dev"
    description: Build web app dev.
    packageFilters:
      scope: studyu_app
      dir-exists: web

  build:web:designer_v2:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --no-tree-shake-icons --dart-define=STUDYU_ENV=.env.dev"
    description: Build web designer_v2 dev.
    packageFilters:
      scope: studyu_designer_v2
      dir-exists: web

  # Used to test Designer "Try out study" feature, where the designer opens the App using the user auth token from designer
  app:web:local:
    run: |
      melos exec -c 1 -- \
        "flutter run lib/main.dart -d chrome --web-port 8080 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_app
    description: Runs app in chrome on port 8080 with local env

  designer_v2:web:local:
    run: |
      melos exec -c 1 -- \
        "flutter run lib/main.dart -d chrome --web-port 8081 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs designer in chrome on port 8081 with local env
