name: studyu

repository: https://github.com/hpi-studyu/studyu

packages:
  - app
  - designer_v2
  - core
  - flutter_common

scripts:
  analyze:
    run: |
      melos exec -c 6 -- \
        "flutter analyze --fatal-infos ."
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  fix:
    run: |
      melos exec -c 6 -- \
        "dart fix --apply"
    description: Fix auto-fixable lint errors

  # todo revert to default line length
  format:
    run: |
      melos exec -c 6 -- \
        "dart format -l 120 ."
    description: Format all code and markdown files

  # todo do not exclude files anymore when line length is set to default
  format:ci:
    run: |
      melos exec -c 6 -- \
        "find . -type f -name '*.dart' ! -name '*.g.dart' ! -path '**/.dart_tool/**' | tr '\n' ' ' | xargs dart format -l 120 --set-exit-if-changed"
    description: Format all code without generated files

  outdated:
    run: |
      melos exec -c 6 --fail-fast -- \
        "dart pub outdated"
    description: Check all outdated dependencies

  upgrade:
    run: |
      dart pub upgrade
      melos exec -c 6 --fail-fast -- \
        "dart pub upgrade" && melos bootstrap
    description: Check all outdated dependencies

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dir-exists: test

  generate:
    run: |
      melos exec -c 1 --fail-fast -- \
        "dart run build_runner build --delete-conflicting-outputs"
    description: Generate files with build_runner
    packageFilters:
      scope: studyu_core

  reset:
    run: |
      git clean -x -d -f -q || true
      melos clean
      melos exec --flutter --concurrency=1 -- "flutter clean"
      melos bootstrap
    description: Reset the workspace to a pristine checkout status.

  app:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8080"
    packageFilters:
        scope: studyu_app
    description: Runs StudyU App with default environment

  designer_v2:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8081"
    packageFilters:
        scope: studyu_designer_v2
    description: Runs StudyU Designer with default environment

  dev:app:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8080 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_app
    description: Runs StudyU App with default environment

  dev:designer_v2:
    run: |
      melos exec -c 1 -- \
        "flutter run -d chrome --web-port 8081 --dart-define=STUDYU_ENV=.env.local"
    packageFilters:
      scope: studyu_designer_v2
    description: Runs StudyU Designer for local development

  build:android:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build apk --multidex"
    description: Build app for Android.
    packageFilters:
      dir-exists: android

  build:ios:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build ipa --no-codesign"
    description: Build app for iOS.
    packageFilters:
      dir-exists: ios

  build:web:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web"
    description: Build app for Web.
    packageFilters:
      scope: [studyu_app, studyu_designer_v2]
      dir-exists: web

  build:web:app:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web"
    description: Build app for Web.
    packageFilters:
      scope: studyu_app

  build:web:designer_v2:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web"
    description: Build designer_v2 for Web.
    packageFilters:
      scope: studyu_designer_v2

  build:web:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --dart-define=STUDYU_ENV=.env.dev"
    description: Build web dev.
    packageFilters:
      scope: [studyu_app, studyu_designer_v2]
      dir-exists: web

  build:web:app:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --dart-define=STUDYU_ENV=.env.dev"
    description: Build web app dev.
    packageFilters:
      scope: studyu_app
      dir-exists: web

  build:web:designer_v2:dev:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --web-renderer auto --dart-define=STUDYU_ENV=.env.dev"
    description: Build web designer_v2 dev.
    packageFilters:
      scope: studyu_designer_v2
      dir-exists: web
