# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

opt_out_usage
# update_fastlane # not working

default_platform(:android)

platform :android do
  desc "Deploy a new version to Google Play"
  lane :deploy_internal do
    flavor = ENV['FLAVOR']
    package_name = "health.studyu.app"
    if flavor == "stg"
      package_name = "health.studyu.app.stg"
    elsif flavor == "dev"
      package_name = "health.studyu.app.dev"
    end

    upload_to_play_store(
      track: 'internal',
      package_name: package_name,
      aab: "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
    )
  end
end
