version: '3'
name: 'studyu'

networks:
  studyu_network:
    name: studyu_network
    driver: bridge
    external: true

services:
  designer_legacy:
    container_name: studyu-designer_legacy
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.single
      args:
        FLUTTER_APP_FOLDER: designer
    ports:
      - 8081:8081
    networks:
      - studyu_network
    volumes:
      # To use the legacy designer instead of the new designer_v2
      # replace designer_v2 with designer in the file nginx/conf.d/designer.conf
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    env_file:
      - ../flutter_common/lib/envs/.env.selfhost
