version: '3'
services:
  app-selfhost:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        FLUTTER_APP_FOLDER: app
        ENV: selfhost
    ports:
      - 8080:80
    networks:
      - studyu-net
    env_file:
      - ../flutter_common/lib/envs/.env.selfhost
networks:
  studyu-net:
    name: studyu_network
