version: '3',
name: 'studyu'

services:
  apps:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        ENV: selfhost
    ports:
      - 80:80
    # - 443:443
    env_file:
      - ../flutter_common/lib/envs/.env.selfhost
    volumes:
      - ./docker/nginx/conf.d /etc/nginx/conf.d
      - ./docker/nginx/.htpasswd /etc/nginx/.htpasswd