version: '3'
name: 'studyu'

services:
  designer_legacy:
    container_name: designer_legacy
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.specifc
      args:
        FLUTTER_APP_FOLDER: designer
    ports:
      - 8081:8081
    volumes:
      # To use the legacy designer instead of the new designer_v2
      # replace designer_v2 with designer in the file nginx/conf.d/designer.conf
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      STUDYU_SUPABASE_PUBLIC_ANON_KEY: ${ANON_KEY}
    env_file:
      - ../flutter_common/lib/envs/.env.selfhost