version: '3'
name: 'studyu'

networks:
  default:
    name: studyu_network

services:
  app:
    container_name: studyu-app
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.single
      args:
        FLUTTER_APP_FOLDER: app
    ports:
      - 8080:8080 # StudyU App
      - 8082:8082 # Supabase Studio (disable if you do not want to self-host Supabase on this machine)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    env_file:
      - ../flutter_common/lib/envs/.env.selfhost
