version: '3'
name: 'studyu'

services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.specifc
      args:
        FLUTTER_APP_FOLDER: app
        # STUDYU_ENV: selfhost
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
