image: cirrusci/flutter:beta

stages:
  - check-format
  - build
  - verify

check-format:
  stage: check-format
  script:
    - flutter format -l 120 -n . --set-exit-if-changed
  tags:
    - app

build:
  stage: build
  script:
    - flutter build aot
  tags:
    - app
    - android

test:
  stage: verify
  script:
    - flutter test
  tags:
    - app
    - android

analyze:
  stage: verify
  script:
    - flutter analyze
  tags:
    - app
    - android
