name: studyu_app
version: 2.12.2
description: Partake in digital N-of-1 trials with the innovative StudyU Health App
publish_to: none
homepage: https://studyu.health
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  camera: ^0.11.3
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  fitbitter:
    # path: ../../fitbitter
    git:
      url: https://github.com/hpi-studyu/fitbitter.git
      ref: master
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.1
  flutter_timezone: ^5.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter_widget_from_html: ^0.17.1
  gauge_indicator: ^0.4.3
  intersperse: ^2.0.0
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_drawing: ^1.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  quiver: ^3.2.2
  rainbow_color: ^2.0.1
  record: ^6.1.2
  sentry_flutter: ^9.7.0
  sentry_logging: ^9.7.0
  shared_preferences: ^2.5.3
  statistics: ^1.2.0
  studyu_core: ^4.7.0
  studyu_flutter_common: ^1.10.0
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3
  timeline_tile: ^2.0.0
  timezone: ^0.10.1
  touchable: ^1.0.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  wakelock_plus: ^1.4.0
  xml: ^6.6.1

#dependency_overrides:
#  flutter_web_auth:
#    git:
#      url: https://github.com/johannesvedder/flutter_web_auth.git
#      ref: fix-android-kotlin

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/fonts/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_bg.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#0175C2" # "#dfdfdf"
    theme_color: "#0175C2" # "#389bea"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png
  # branding: assets/icon/logo.png
  # branding_bottom_padding: 24
  android_12:
    image: assets/icon/icon_android12.png
    color: "#ffffff"
    # icon_background_color: "#ffffff"
    # branding: assets/icon/logo.png
  fullscreen: true
  # web: false
