version: '3.8'
name: 'studyu_app'

networks:
  default:
    name: studyu_network
    external: true

services:
  web:
    container_name: studyu-app
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/studyu/Dockerfile
      args:
        FLUTTER_APP_FOLDER: app
    environment:
      - STUDYU_COMPONENT=app
    volumes:
      - ../nginx/studyu:/etc/nginx/templates:ro
    env_file:
      - ../../flutter_common/lib/envs/.env.local
