version: '3.8'
name: 'studyu_designer'

networks:
  default:
    name: studyu_network
    external: true

services:
  web:
    container_name: studyu-designer
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/studyu/Dockerfile
      args:
        FLUTTER_APP_FOLDER: designer_v2
    ports:
      - 8081:8081
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
    env_file:
      - ../../flutter_common/lib/envs/.env.local
