version: '3'
name: 'studyu'

services:
  autodocs:
    image: ghcr.io/k1low/tbls
    depends_on:
      db:
        condition: service_healthy
    command:
      - doc
      - --force
      - postgres://postgres:${POSTGRES_PASSWORD}@supabase-db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      - output
    working_dir: /work
    volumes:
      - ${DB_DOCS_DEST}:/work/output
