// Mocks generated by Mockito 5.4.6 from annotations
// in studyu_designer_v2/test/repositories/study_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i20;

import 'package:flutter/services.dart' as _i21;
import 'package:flutter/widgets.dart' as _i9;
import 'package:go_router/src/configuration.dart' as _i8;
import 'package:go_router/src/delegate.dart' as _i10;
import 'package:go_router/src/information_provider.dart' as _i11;
import 'package:go_router/src/match.dart' as _i19;
import 'package:go_router/src/parser.dart' as _i12;
import 'package:go_router/src/router.dart' as _i18;
import 'package:go_router/src/state.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:rxdart/subjects.dart' as _i6;
import 'package:studyu_core/core.dart' as _i4;
import 'package:studyu_designer_v2/features/dashboard/studies_filter.dart'
    as _i14;
import 'package:studyu_designer_v2/features/dashboard/studies_filter/filter_types.dart'
    as _i15;
import 'package:studyu_designer_v2/features/dashboard/studies_table.dart'
    as _i13;
import 'package:studyu_designer_v2/repositories/api_client.dart' as _i3;
import 'package:studyu_designer_v2/repositories/auth_repository.dart' as _i17;
import 'package:studyu_designer_v2/services/notification_service.dart' as _i22;
import 'package:studyu_designer_v2/services/notification_types.dart' as _i23;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudiesPage_1 extends _i1.SmartFake implements _i3.StudiesPage {
  _FakeStudiesPage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudy_2 extends _i1.SmartFake implements _i4.Study {
  _FakeStudy_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudyInvite_3 extends _i1.SmartFake implements _i4.StudyInvite {
  _FakeStudyInvite_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppConfig_4 extends _i1.SmartFake implements _i4.AppConfig {
  _FakeAppConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudyUUser_5 extends _i1.SmartFake implements _i4.StudyUUser {
  _FakeStudyUUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudyFitbitCredentials_6 extends _i1.SmartFake
    implements _i4.StudyFitbitCredentials {
  _FakeStudyFitbitCredentials_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_7<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_8 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBehaviorSubject_9<T> extends _i1.SmartFake
    implements _i6.BehaviorSubject<T> {
  _FakeBehaviorSubject_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_10 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_11 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterState_12 extends _i1.SmartFake implements _i7.GoRouterState {
  _FakeGoRouterState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_13 extends _i1.SmartFake
    implements _i8.RouteConfiguration {
  _FakeRouteConfiguration_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_14 extends _i1.SmartFake
    implements _i9.BackButtonDispatcher {
  _FakeBackButtonDispatcher_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_15 extends _i1.SmartFake
    implements _i10.GoRouterDelegate {
  _FakeGoRouterDelegate_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_16 extends _i1.SmartFake
    implements _i11.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_17 extends _i1.SmartFake
    implements _i12.GoRouteInformationParser {
  _FakeGoRouteInformationParser_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteInformation_18 extends _i1.SmartFake
    implements _i9.RouteInformation {
  _FakeRouteInformation_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StudyUApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudyUApiClient extends _i1.Mock implements _i3.StudyUApiClient {
  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
            returnValueForMissingStub: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  int get testDelayMilliseconds =>
      (super.noSuchMethod(
            Invocation.getter(#testDelayMilliseconds),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<List<_i4.StudySubject>> deleteParticipants(
    _i4.Study? study,
    List<_i4.StudySubject>? participants,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteParticipants, [study, participants]),
            returnValue: _i5.Future<List<_i4.StudySubject>>.value(
              <_i4.StudySubject>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i4.StudySubject>>.value(
              <_i4.StudySubject>[],
            ),
          )
          as _i5.Future<List<_i4.StudySubject>>);

  @override
  _i5.Future<List<_i4.Study>> getUserStudies({
    bool? withParticipantActivity = false,
    bool? forDashboardDisplay = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStudies, [], {
              #withParticipantActivity: withParticipantActivity,
              #forDashboardDisplay: forDashboardDisplay,
            }),
            returnValue: _i5.Future<List<_i4.Study>>.value(<_i4.Study>[]),
            returnValueForMissingStub: _i5.Future<List<_i4.Study>>.value(
              <_i4.Study>[],
            ),
          )
          as _i5.Future<List<_i4.Study>>);

  @override
  _i5.Future<_i3.StudiesPage> getUserStudiesPage({
    required int? offset,
    required int? limit,
    required _i13.StudiesTableColumn? sortBy,
    required bool? ascending,
    required _i14.StudiesFilter? preset,
    required _i2.User? currentUser,
    String? searchQuery,
    _i15.FilterGroup? advancedFilter,
    List<String>? excludeIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStudiesPage, [], {
              #offset: offset,
              #limit: limit,
              #sortBy: sortBy,
              #ascending: ascending,
              #preset: preset,
              #currentUser: currentUser,
              #searchQuery: searchQuery,
              #advancedFilter: advancedFilter,
              #excludeIds: excludeIds,
            }),
            returnValue: _i5.Future<_i3.StudiesPage>.value(
              _FakeStudiesPage_1(
                this,
                Invocation.method(#getUserStudiesPage, [], {
                  #offset: offset,
                  #limit: limit,
                  #sortBy: sortBy,
                  #ascending: ascending,
                  #preset: preset,
                  #currentUser: currentUser,
                  #searchQuery: searchQuery,
                  #advancedFilter: advancedFilter,
                  #excludeIds: excludeIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.StudiesPage>.value(
              _FakeStudiesPage_1(
                this,
                Invocation.method(#getUserStudiesPage, [], {
                  #offset: offset,
                  #limit: limit,
                  #sortBy: sortBy,
                  #ascending: ascending,
                  #preset: preset,
                  #currentUser: currentUser,
                  #searchQuery: searchQuery,
                  #advancedFilter: advancedFilter,
                  #excludeIds: excludeIds,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.StudiesPage>);

  @override
  _i5.Future<List<_i4.Study>> getPinnedUserStudies({
    required Set<String>? pinnedIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPinnedUserStudies, [], {
              #pinnedIds: pinnedIds,
            }),
            returnValue: _i5.Future<List<_i4.Study>>.value(<_i4.Study>[]),
            returnValueForMissingStub: _i5.Future<List<_i4.Study>>.value(
              <_i4.Study>[],
            ),
          )
          as _i5.Future<List<_i4.Study>>);

  @override
  _i5.Future<_i4.Study> fetchStudy(
    String? studyId, {
    bool? withParticipantActivity = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchStudy,
              [studyId],
              {#withParticipantActivity: withParticipantActivity},
            ),
            returnValue: _i5.Future<_i4.Study>.value(
              _FakeStudy_2(
                this,
                Invocation.method(
                  #fetchStudy,
                  [studyId],
                  {#withParticipantActivity: withParticipantActivity},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i4.Study>.value(
              _FakeStudy_2(
                this,
                Invocation.method(
                  #fetchStudy,
                  [studyId],
                  {#withParticipantActivity: withParticipantActivity},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Study>);

  @override
  _i5.Future<void> deleteStudy(_i4.Study? study) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudy, [study]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.Study> saveStudy(_i4.Study? study) =>
      (super.noSuchMethod(
            Invocation.method(#saveStudy, [study]),
            returnValue: _i5.Future<_i4.Study>.value(
              _FakeStudy_2(this, Invocation.method(#saveStudy, [study])),
            ),
            returnValueForMissingStub: _i5.Future<_i4.Study>.value(
              _FakeStudy_2(this, Invocation.method(#saveStudy, [study])),
            ),
          )
          as _i5.Future<_i4.Study>);

  @override
  _i5.Future<_i4.StudyInvite> fetchStudyInvite(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudyInvite, [code]),
            returnValue: _i5.Future<_i4.StudyInvite>.value(
              _FakeStudyInvite_3(
                this,
                Invocation.method(#fetchStudyInvite, [code]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i4.StudyInvite>.value(
              _FakeStudyInvite_3(
                this,
                Invocation.method(#fetchStudyInvite, [code]),
              ),
            ),
          )
          as _i5.Future<_i4.StudyInvite>);

  @override
  _i5.Future<_i4.Study> fetchStudyFromInvite(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudyFromInvite, [code]),
            returnValue: _i5.Future<_i4.Study>.value(
              _FakeStudy_2(
                this,
                Invocation.method(#fetchStudyFromInvite, [code]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i4.Study>.value(
              _FakeStudy_2(
                this,
                Invocation.method(#fetchStudyFromInvite, [code]),
              ),
            ),
          )
          as _i5.Future<_i4.Study>);

  @override
  _i5.Future<_i4.StudyInvite> saveStudyInvite(_i4.StudyInvite? invite) =>
      (super.noSuchMethod(
            Invocation.method(#saveStudyInvite, [invite]),
            returnValue: _i5.Future<_i4.StudyInvite>.value(
              _FakeStudyInvite_3(
                this,
                Invocation.method(#saveStudyInvite, [invite]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i4.StudyInvite>.value(
              _FakeStudyInvite_3(
                this,
                Invocation.method(#saveStudyInvite, [invite]),
              ),
            ),
          )
          as _i5.Future<_i4.StudyInvite>);

  @override
  _i5.Future<void> deleteStudyInvite(_i4.StudyInvite? invite) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudyInvite, [invite]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.AppConfig> fetchAppConfig() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAppConfig, []),
            returnValue: _i5.Future<_i4.AppConfig>.value(
              _FakeAppConfig_4(this, Invocation.method(#fetchAppConfig, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i4.AppConfig>.value(
              _FakeAppConfig_4(this, Invocation.method(#fetchAppConfig, [])),
            ),
          )
          as _i5.Future<_i4.AppConfig>);

  @override
  _i5.Future<_i4.StudyUUser> fetchUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [userId]),
            returnValue: _i5.Future<_i4.StudyUUser>.value(
              _FakeStudyUUser_5(this, Invocation.method(#fetchUser, [userId])),
            ),
            returnValueForMissingStub: _i5.Future<_i4.StudyUUser>.value(
              _FakeStudyUUser_5(this, Invocation.method(#fetchUser, [userId])),
            ),
          )
          as _i5.Future<_i4.StudyUUser>);

  @override
  _i5.Future<_i4.StudyUUser> saveUser(_i4.StudyUUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i5.Future<_i4.StudyUUser>.value(
              _FakeStudyUUser_5(this, Invocation.method(#saveUser, [user])),
            ),
            returnValueForMissingStub: _i5.Future<_i4.StudyUUser>.value(
              _FakeStudyUUser_5(this, Invocation.method(#saveUser, [user])),
            ),
          )
          as _i5.Future<_i4.StudyUUser>);

  @override
  _i5.Future<_i4.StudyFitbitCredentials> saveStudyFitbitCredentials(
    _i4.StudyFitbitCredentials? credentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveStudyFitbitCredentials, [credentials]),
            returnValue: _i5.Future<_i4.StudyFitbitCredentials>.value(
              _FakeStudyFitbitCredentials_6(
                this,
                Invocation.method(#saveStudyFitbitCredentials, [credentials]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i4.StudyFitbitCredentials>.value(
                  _FakeStudyFitbitCredentials_6(
                    this,
                    Invocation.method(#saveStudyFitbitCredentials, [
                      credentials,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i4.StudyFitbitCredentials>);

  @override
  _i5.Future<_i4.StudyFitbitCredentials> fetchStudyFitbitCredentials(
    String? studyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudyFitbitCredentials, [studyId]),
            returnValue: _i5.Future<_i4.StudyFitbitCredentials>.value(
              _FakeStudyFitbitCredentials_6(
                this,
                Invocation.method(#fetchStudyFitbitCredentials, [studyId]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i4.StudyFitbitCredentials>.value(
                  _FakeStudyFitbitCredentials_6(
                    this,
                    Invocation.method(#fetchStudyFitbitCredentials, [studyId]),
                  ),
                ),
          )
          as _i5.Future<_i4.StudyFitbitCredentials>);

  @override
  _i5.Future<void> deleteStudyFitbitCredentials(
    _i4.StudyFitbitCredentials? credentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudyFitbitCredentials, [credentials]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<T>> deleteAll<T extends _i4.SupabaseObject>(
    Map<String, Object>? selectionCriteria,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [selectionCriteria]),
            returnValue: _i5.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
          )
          as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> getAll<T extends _i4.SupabaseObject>({
    List<String>? selectedColumns = const ['*'],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#selectedColumns: selectedColumns}),
            returnValue: _i5.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
          )
          as _i5.Future<List<T>>);

  @override
  _i5.Future<T> getById<T extends _i4.SupabaseObject>(
    String? id, {
    List<String>? selectedColumns = const ['*'],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getById,
              [id],
              {#selectedColumns: selectedColumns},
            ),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getById,
                      [id],
                      {#selectedColumns: selectedColumns},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(
                    #getById,
                    [id],
                    {#selectedColumns: selectedColumns},
                  ),
                ),
            returnValueForMissingStub:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getById,
                      [id],
                      {#selectedColumns: selectedColumns},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(
                    #getById,
                    [id],
                    {#selectedColumns: selectedColumns},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> getByColumn<T extends _i4.SupabaseObject>(
    String? colName,
    String? value, {
    List<String>? selectedColumns = const ['*'],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByColumn,
              [colName, value],
              {#selectedColumns: selectedColumns},
            ),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getByColumn,
                      [colName, value],
                      {#selectedColumns: selectedColumns},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(
                    #getByColumn,
                    [colName, value],
                    {#selectedColumns: selectedColumns},
                  ),
                ),
            returnValueForMissingStub:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getByColumn,
                      [colName, value],
                      {#selectedColumns: selectedColumns},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_7<T>(
                  this,
                  Invocation.method(
                    #getByColumn,
                    [colName, value],
                    {#selectedColumns: selectedColumns},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<dynamic> executeRpc(
    String? functionName, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeRpc, [functionName], {#params: params}),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  List<T> deserializeList<T extends _i4.SupabaseObject>(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeList, [data]),
            returnValue: <T>[],
            returnValueForMissingStub: <T>[],
          )
          as List<T>);

  @override
  T deserializeObject<T extends _i4.SupabaseObject>(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeObject, [data]),
            returnValue: _i16.dummyValue<T>(
              this,
              Invocation.method(#deserializeObject, [data]),
            ),
            returnValueForMissingStub: _i16.dummyValue<T>(
              this,
              Invocation.method(#deserializeObject, [data]),
            ),
          )
          as T);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i17.AuthRepository {
  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
            returnValueForMissingStub: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i2.GoTrueClient get authClient =>
      (super.noSuchMethod(
            Invocation.getter(#authClient),
            returnValue: _FakeGoTrueClient_8(
              this,
              Invocation.getter(#authClient),
            ),
            returnValueForMissingStub: _FakeGoTrueClient_8(
              this,
              Invocation.getter(#authClient),
            ),
          )
          as _i2.GoTrueClient);

  @override
  bool get allowPasswordReset =>
      (super.noSuchMethod(
            Invocation.getter(#allowPasswordReset),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set allowPasswordReset(bool? value) => super.noSuchMethod(
    Invocation.setter(#allowPasswordReset, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.BehaviorSubject<_i2.User?> watchAuthStateChanges({
    bool? emitLastEvent = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAuthStateChanges, [], {
              #emitLastEvent: emitLastEvent,
            }),
            returnValue: _FakeBehaviorSubject_9<_i2.User?>(
              this,
              Invocation.method(#watchAuthStateChanges, [], {
                #emitLastEvent: emitLastEvent,
              }),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_9<_i2.User?>(
              this,
              Invocation.method(#watchAuthStateChanges, [], {
                #emitLastEvent: emitLastEvent,
              }),
            ),
          )
          as _i6.BehaviorSubject<_i2.User?>);

  @override
  _i5.Future<_i2.AuthResponse> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_10(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_10(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signInWith({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWith, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_10(
                this,
                Invocation.method(#signInWith, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_10(
                this,
                Invocation.method(#signInWith, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPasswordForEmail({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordForEmail, [], {#email: email}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserResponse> updateUser({required String? newPassword}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {#newPassword: newPassword}),
            returnValue: _i5.Future<_i2.UserResponse>.value(
              _FakeUserResponse_11(
                this,
                Invocation.method(#updateUser, [], {#newPassword: newPassword}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserResponse>.value(
              _FakeUserResponse_11(
                this,
                Invocation.method(#updateUser, [], {#newPassword: newPassword}),
              ),
            ),
          )
          as _i5.Future<_i2.UserResponse>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> onAppStart() =>
      (super.noSuchMethod(
            Invocation.method(#onAppStart, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i18.GoRouter {
  @override
  _i7.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_12(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeGoRouterState_12(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.GoRouterState);

  @override
  _i8.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_13(
              this,
              Invocation.getter(#configuration),
            ),
            returnValueForMissingStub: _FakeRouteConfiguration_13(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i8.RouteConfiguration);

  @override
  _i9.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_14(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
            returnValueForMissingStub: _FakeBackButtonDispatcher_14(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i9.BackButtonDispatcher);

  @override
  _i10.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_15(
              this,
              Invocation.getter(#routerDelegate),
            ),
            returnValueForMissingStub: _FakeGoRouterDelegate_15(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i10.GoRouterDelegate);

  @override
  _i11.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_16(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationProvider_16(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i11.GoRouteInformationProvider);

  @override
  _i12.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_17(
              this,
              Invocation.getter(#routeInformationParser),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationParser_17(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i12.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set configuration(_i8.RouteConfiguration? value) => super.noSuchMethod(
    Invocation.setter(#configuration, value),
    returnValueForMissingStub: null,
  );

  @override
  set routerDelegate(_i10.GoRouterDelegate? value) => super.noSuchMethod(
    Invocation.setter(#routerDelegate, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationProvider(_i11.GoRouteInformationProvider? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, value),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationParser(_i12.GoRouteInformationParser? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, value),
        returnValueForMissingStub: null,
      );

  @override
  bool canPop() =>
      (super.noSuchMethod(
            Invocation.method(#canPop, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
            returnValueForMissingStub: _i16.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i19.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoRouteInformationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouteInformationProvider extends _i1.Mock
    implements _i11.GoRouteInformationProvider {
  @override
  _i9.RouteInformation get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeRouteInformation_18(
              this,
              Invocation.getter(#value),
            ),
            returnValueForMissingStub: _FakeRouteInformation_18(
              this,
              Invocation.getter(#value),
            ),
          )
          as _i9.RouteInformation);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void routerReportsNewRouteInformation(
    _i9.RouteInformation? routeInformation, {
    _i9.RouteInformationReportingType? type =
        _i9.RouteInformationReportingType.none,
  }) => super.noSuchMethod(
    Invocation.method(
      #routerReportsNewRouteInformation,
      [routeInformation],
      {#type: type},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<T?> push<T>(
    String? location, {
    required _i19.RouteMatchList? base,
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#base: base, #extra: extra}),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(String? location, {required _i19.RouteMatchList? matchList}) =>
      super.noSuchMethod(
        Invocation.method(#restore, [location], {#matchList: matchList}),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<T?> pushReplacement<T>(
    String? location, {
    required _i19.RouteMatchList? base,
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacement,
              [location],
              {#base: base, #extra: extra},
            ),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<T?> replace<T>(
    String? location, {
    required _i19.RouteMatchList? base,
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replace,
              [location],
              {#base: base, #extra: extra},
            ),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> didPushRouteInformation(
    _i9.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool handleStartBackGesture(_i21.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i21.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i20.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i20.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i20.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i20.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i5.Future<_i20.AppExitResponse>.value(
              _i20.AppExitResponse.exit,
            ),
            returnValueForMissingStub: _i5.Future<_i20.AppExitResponse>.value(
              _i20.AppExitResponse.exit,
            ),
          )
          as _i5.Future<_i20.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i22.NotificationService {
  @override
  _i5.Stream<_i23.NotificationIntent> watchNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, []),
            returnValue: _i5.Stream<_i23.NotificationIntent>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i23.NotificationIntent>.empty(),
          )
          as _i5.Stream<_i23.NotificationIntent>);

  @override
  void showMessage(String? message, {List<_i23.NotificationAction>? actions}) =>
      super.noSuchMethod(
        Invocation.method(#showMessage, [message], {#actions: actions}),
        returnValueForMissingStub: null,
      );

  @override
  void show(
    _i23.NotificationIntent? notification, {
    List<_i23.NotificationAction>? actions,
  }) => super.noSuchMethod(
    Invocation.method(#show, [notification], {#actions: actions}),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i16.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i16.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i16.dummyValue<String>(this, Invocation.getter(#aud)),
            returnValueForMissingStub: _i16.dummyValue<String>(
              this,
              Invocation.getter(#aud),
            ),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
            returnValueForMissingStub: _i16.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
