# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :upload_testflight do
    app_store_connect_api_key(
      key_id: ENV['FASTLANE_APP_IOS_KEY_ID'],
      issuer_id: ENV['FASTLANE_APP_IOS_ISSUER_ID'],
      key_content: ENV['FASTLANE_APP_IOS_KEY_CONTENT']
    )
    # sync_code_signing(type: "appstore")
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    # build_app
    # pilot
    # match(      
    #   type: 'appstore', 
    #   app_identifier: ["health.studyu.app"],
    #   readonly: true
    # )
    # cert
    sigh(
      team_id: "PG566C9XUK",
      force: true
    )
    build_app(
      export_method: "app-store",
    )
    pilot
  end
end
