# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :upload_testflight do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    app_store_connect_api_key(
      key_id: ENV['FASTLANE_APP_IOS_KEY_ID'],
      issuer_id: ENV['FASTLANE_APP_IOS_ISSUER_ID'],
      key_content: ENV['FASTLANE_APP_IOS_KEY_CONTENT']
    )
    # sync_code_signing(type: "appstore")
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    # build_app
    # pilot
    # match(      
    #   type: 'appstore', 
    #   app_identifier: ["health.studyu.app"],
    #   readonly: true
    # )
    get_certificates(
      team_id: "PG566C9XUK",
      keychain_path: "~/Library/Keychains/#{keychain_name}-db",
      keychain_password: keychain_password 
    )
    get_provisioning_profile(
      team_id: "PG566C9XUK",
      force: true
    )
    build_app(
      export_method: "app-store",
    )
    pilot

    delete_temp_keychain(keychain_name)
  end
end
