// Mocks generated by Mockito from annotations
// in studyu_designer_v2/test/features/dashboard/dashboard_controller_pagination_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i13;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:rxdart/subjects.dart' as _i7;
import 'package:studyu_core/core.dart' as _i8;
import 'package:studyu_designer_v2/features/dashboard/studies_filter.dart'
    as _i14;
import 'package:studyu_designer_v2/features/dashboard/studies_filter/filter_types.dart'
    as _i15;
import 'package:studyu_designer_v2/repositories/api_client.dart' as _i2;
import 'package:studyu_designer_v2/repositories/auth_repository.dart' as _i3;
import 'package:studyu_designer_v2/repositories/model_repository.dart' as _i4;
import 'package:studyu_designer_v2/repositories/model_repository_events.dart'
    as _i12;
import 'package:studyu_designer_v2/repositories/study_repository.dart' as _i9;
import 'package:studyu_designer_v2/repositories/study_repository_interface.dart'
    as _i5;
import 'package:studyu_designer_v2/repositories/user_repository.dart' as _i17;
import 'package:studyu_designer_v2/utils/model_action.dart' as _i16;
import 'package:supabase/supabase.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStudyUApi_0 extends _i1.SmartFake implements _i2.StudyUApi {
  _FakeStudyUApi_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIAuthRepository_1 extends _i1.SmartFake
    implements _i3.IAuthRepository {
  _FakeIAuthRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIModelRepositoryDelegate_2<T> extends _i1.SmartFake
    implements _i4.IModelRepositoryDelegate<T> {
  _FakeIModelRepositoryDelegate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudiesPage_3 extends _i1.SmartFake implements _i5.StudiesPage {
  _FakeStudiesPage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWrappedModel_4<T> extends _i1.SmartFake
    implements _i4.WrappedModel<T> {
  _FakeWrappedModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_5 extends _i1.SmartFake
    implements _i6.SupabaseClient {
  _FakeSupabaseClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_6 extends _i1.SmartFake implements _i6.GoTrueClient {
  _FakeGoTrueClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBehaviorSubject_7<T> extends _i1.SmartFake
    implements _i7.BehaviorSubject<T> {
  _FakeBehaviorSubject_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_8 extends _i1.SmartFake implements _i6.AuthResponse {
  _FakeAuthResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_9 extends _i1.SmartFake implements _i6.UserResponse {
  _FakeUserResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudyUUser_10 extends _i1.SmartFake implements _i8.StudyUUser {
  _FakeStudyUUser_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StudyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudyRepository extends _i1.Mock implements _i9.StudyRepository {
  @override
  _i2.StudyUApi get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeStudyUApi_0(this, Invocation.getter(#apiClient)),
            returnValueForMissingStub: _FakeStudyUApi_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.StudyUApi);

  @override
  _i3.IAuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeIAuthRepository_1(
              this,
              Invocation.getter(#authRepository),
            ),
            returnValueForMissingStub: _FakeIAuthRepository_1(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i3.IAuthRepository);

  @override
  _i10.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i11.dummyValue<_i10.Ref>(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub: _i11.dummyValue<_i10.Ref>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i10.Ref);

  @override
  _i4.IModelRepositoryDelegate<_i8.Study> get delegate =>
      (super.noSuchMethod(
            Invocation.getter(#delegate),
            returnValue: _FakeIModelRepositoryDelegate_2<_i8.Study>(
              this,
              Invocation.getter(#delegate),
            ),
            returnValueForMissingStub:
                _FakeIModelRepositoryDelegate_2<_i8.Study>(
                  this,
                  Invocation.getter(#delegate),
                ),
          )
          as _i4.IModelRepositoryDelegate<_i8.Study>);

  @override
  Map<String, _i7.BehaviorSubject<_i4.WrappedModel<_i8.Study>>>
  get modelStreamControllers =>
      (super.noSuchMethod(
            Invocation.getter(#modelStreamControllers),
            returnValue:
                <String, _i7.BehaviorSubject<_i4.WrappedModel<_i8.Study>>>{},
            returnValueForMissingStub:
                <String, _i7.BehaviorSubject<_i4.WrappedModel<_i8.Study>>>{},
          )
          as Map<String, _i7.BehaviorSubject<_i4.WrappedModel<_i8.Study>>>);

  @override
  Map<String, _i7.BehaviorSubject<_i12.ModelEvent<_i8.Study>>>
  get modelEventsStreamControllers =>
      (super.noSuchMethod(
            Invocation.getter(#modelEventsStreamControllers),
            returnValue:
                <String, _i7.BehaviorSubject<_i12.ModelEvent<_i8.Study>>>{},
            returnValueForMissingStub:
                <String, _i7.BehaviorSubject<_i12.ModelEvent<_i8.Study>>>{},
          )
          as Map<String, _i7.BehaviorSubject<_i12.ModelEvent<_i8.Study>>>);

  @override
  Map<String, _i4.WrappedModel<_i8.Study>> get modelCache =>
      (super.noSuchMethod(
            Invocation.getter(#modelCache),
            returnValue: <String, _i4.WrappedModel<_i8.Study>>{},
            returnValueForMissingStub: <String, _i4.WrappedModel<_i8.Study>>{},
          )
          as Map<String, _i4.WrappedModel<_i8.Study>>);

  @override
  String getKey(_i8.Study? model) =>
      (super.noSuchMethod(
            Invocation.method(#getKey, [model]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getKey, [model]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#getKey, [model]),
            ),
          )
          as String);

  @override
  _i13.Future<void> deleteParticipants(_i8.Study? study) =>
      (super.noSuchMethod(
            Invocation.method(#deleteParticipants, [study]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> launch(_i8.Study? study) =>
      (super.noSuchMethod(
            Invocation.method(#launch, [study]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> duplicateAndSave(_i8.Study? model) =>
      (super.noSuchMethod(
            Invocation.method(#duplicateAndSave, [model]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> close(_i8.Study? study) =>
      (super.noSuchMethod(
            Invocation.method(#close, [study]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i5.StudiesPage> fetchPage({
    required int? offset,
    required int? limit,
    required _i5.StudiesTableColumn? sortBy,
    required bool? ascending,
    required _i14.StudiesFilter? preset,
    required _i6.User? currentUser,
    String? searchQuery,
    _i15.FilterGroup? advancedFilter,
    List<String>? excludeIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPage, [], {
              #offset: offset,
              #limit: limit,
              #sortBy: sortBy,
              #ascending: ascending,
              #preset: preset,
              #currentUser: currentUser,
              #searchQuery: searchQuery,
              #advancedFilter: advancedFilter,
              #excludeIds: excludeIds,
            }),
            returnValue: _i13.Future<_i5.StudiesPage>.value(
              _FakeStudiesPage_3(
                this,
                Invocation.method(#fetchPage, [], {
                  #offset: offset,
                  #limit: limit,
                  #sortBy: sortBy,
                  #ascending: ascending,
                  #preset: preset,
                  #currentUser: currentUser,
                  #searchQuery: searchQuery,
                  #advancedFilter: advancedFilter,
                  #excludeIds: excludeIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i5.StudiesPage>.value(
              _FakeStudiesPage_3(
                this,
                Invocation.method(#fetchPage, [], {
                  #offset: offset,
                  #limit: limit,
                  #sortBy: sortBy,
                  #ascending: ascending,
                  #preset: preset,
                  #currentUser: currentUser,
                  #searchQuery: searchQuery,
                  #advancedFilter: advancedFilter,
                  #excludeIds: excludeIds,
                }),
              ),
            ),
          )
          as _i13.Future<_i5.StudiesPage>);

  @override
  _i13.Future<List<_i8.Study>> fetchPinned(Set<String>? pinnedIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPinned, [pinnedIds]),
            returnValue: _i13.Future<List<_i8.Study>>.value(<_i8.Study>[]),
            returnValueForMissingStub: _i13.Future<List<_i8.Study>>.value(
              <_i8.Study>[],
            ),
          )
          as _i13.Future<List<_i8.Study>>);

  @override
  List<_i16.ModelAction<dynamic>> availableActions(_i8.Study? model) =>
      (super.noSuchMethod(
            Invocation.method(#availableActions, [model]),
            returnValue: <_i16.ModelAction<dynamic>>[],
            returnValueForMissingStub: <_i16.ModelAction<dynamic>>[],
          )
          as List<_i16.ModelAction<dynamic>>);

  @override
  _i4.WrappedModel<_i8.Study>? get(String? modelId, {bool? strict = false}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [modelId], {#strict: strict}),
            returnValueForMissingStub: null,
          )
          as _i4.WrappedModel<_i8.Study>?);

  @override
  _i13.Future<List<_i4.WrappedModel<_i8.Study>>> fetchAll() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAll, []),
            returnValue: _i13.Future<List<_i4.WrappedModel<_i8.Study>>>.value(
              <_i4.WrappedModel<_i8.Study>>[],
            ),
            returnValueForMissingStub:
                _i13.Future<List<_i4.WrappedModel<_i8.Study>>>.value(
                  <_i4.WrappedModel<_i8.Study>>[],
                ),
          )
          as _i13.Future<List<_i4.WrappedModel<_i8.Study>>>);

  @override
  _i13.Future<_i4.WrappedModel<_i8.Study>> fetch(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [modelId]),
            returnValue: _i13.Future<_i4.WrappedModel<_i8.Study>>.value(
              _FakeWrappedModel_4<_i8.Study>(
                this,
                Invocation.method(#fetch, [modelId]),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i4.WrappedModel<_i8.Study>>.value(
                  _FakeWrappedModel_4<_i8.Study>(
                    this,
                    Invocation.method(#fetch, [modelId]),
                  ),
                ),
          )
          as _i13.Future<_i4.WrappedModel<_i8.Study>>);

  @override
  _i13.Future<_i4.WrappedModel<_i8.Study>?> save(
    _i8.Study? model, {
    bool? runOptimistically = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #save,
              [model],
              {#runOptimistically: runOptimistically},
            ),
            returnValue: _i13.Future<_i4.WrappedModel<_i8.Study>?>.value(),
            returnValueForMissingStub:
                _i13.Future<_i4.WrappedModel<_i8.Study>?>.value(),
          )
          as _i13.Future<_i4.WrappedModel<_i8.Study>?>);

  @override
  _i13.Future<void> delete(String? modelId, {bool? runOptimistically = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [modelId],
              {#runOptimistically: runOptimistically},
            ),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Stream<List<_i4.WrappedModel<_i8.Study>>> watchAll({
    bool? fetchOnSubscribe = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {
              #fetchOnSubscribe: fetchOnSubscribe,
            }),
            returnValue: _i13.Stream<List<_i4.WrappedModel<_i8.Study>>>.empty(),
            returnValueForMissingStub:
                _i13.Stream<List<_i4.WrappedModel<_i8.Study>>>.empty(),
          )
          as _i13.Stream<List<_i4.WrappedModel<_i8.Study>>>);

  @override
  _i13.Stream<_i4.WrappedModel<_i8.Study>> watch(
    String? modelIdParam, {
    bool? fetchOnSubscribe = true,
    bool? emitLastEvent = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watch,
              [modelIdParam],
              {
                #fetchOnSubscribe: fetchOnSubscribe,
                #emitLastEvent: emitLastEvent,
              },
            ),
            returnValue: _i13.Stream<_i4.WrappedModel<_i8.Study>>.empty(),
            returnValueForMissingStub:
                _i13.Stream<_i4.WrappedModel<_i8.Study>>.empty(),
          )
          as _i13.Stream<_i4.WrappedModel<_i8.Study>>);

  @override
  _i13.Stream<_i12.ModelEvent<_i8.Study>> watchAllChanges() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllChanges, []),
            returnValue: _i13.Stream<_i12.ModelEvent<_i8.Study>>.empty(),
            returnValueForMissingStub:
                _i13.Stream<_i12.ModelEvent<_i8.Study>>.empty(),
          )
          as _i13.Stream<_i12.ModelEvent<_i8.Study>>);

  @override
  _i13.Stream<_i12.ModelEvent<_i8.Study>> watchChanges(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#watchChanges, [modelId]),
            returnValue: _i13.Stream<_i12.ModelEvent<_i8.Study>>.empty(),
            returnValueForMissingStub:
                _i13.Stream<_i12.ModelEvent<_i8.Study>>.empty(),
          )
          as _i13.Stream<_i12.ModelEvent<_i8.Study>>);

  @override
  _i13.Future<_i4.WrappedModel<_i8.Study>?> ensurePersisted(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#ensurePersisted, [modelId]),
            returnValue: _i13.Future<_i4.WrappedModel<_i8.Study>?>.value(),
            returnValueForMissingStub:
                _i13.Future<_i4.WrappedModel<_i8.Study>?>.value(),
          )
          as _i13.Future<_i4.WrappedModel<_i8.Study>?>);

  @override
  _i4.WrappedModel<_i8.Study> upsertLocally(
    _i8.Study? newModel, {
    bool? emitUpdate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertLocally,
              [newModel],
              {#emitUpdate: emitUpdate},
            ),
            returnValue: _FakeWrappedModel_4<_i8.Study>(
              this,
              Invocation.method(
                #upsertLocally,
                [newModel],
                {#emitUpdate: emitUpdate},
              ),
            ),
            returnValueForMissingStub: _FakeWrappedModel_4<_i8.Study>(
              this,
              Invocation.method(
                #upsertLocally,
                [newModel],
                {#emitUpdate: emitUpdate},
              ),
            ),
          )
          as _i4.WrappedModel<_i8.Study>);

  @override
  List<_i4.WrappedModel<_i8.Study>> upsertAllLocally(
    List<_i8.Study>? newModels, {
    bool? emitUpdate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertAllLocally,
              [newModels],
              {#emitUpdate: emitUpdate},
            ),
            returnValue: <_i4.WrappedModel<_i8.Study>>[],
            returnValueForMissingStub: <_i4.WrappedModel<_i8.Study>>[],
          )
          as List<_i4.WrappedModel<_i8.Study>>);

  @override
  void emitUpdate() => super.noSuchMethod(
    Invocation.method(#emitUpdate, []),
    returnValueForMissingStub: null,
  );

  @override
  void emitModelEvent(_i12.ModelEvent<_i8.Study>? event) => super.noSuchMethod(
    Invocation.method(#emitModelEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emitError(
    _i13.StreamController<dynamic>? controller,
    Object? e,
    StackTrace? stackTrace,
  ) => super.noSuchMethod(
    Invocation.method(#emitError, [controller, e, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void markForRefresh(String? modelId) => super.noSuchMethod(
    Invocation.method(#markForRefresh, [modelId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i6.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_5(
              this,
              Invocation.getter(#supabaseClient),
            ),
            returnValueForMissingStub: _FakeSupabaseClient_5(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i6.SupabaseClient);

  @override
  _i6.GoTrueClient get authClient =>
      (super.noSuchMethod(
            Invocation.getter(#authClient),
            returnValue: _FakeGoTrueClient_6(
              this,
              Invocation.getter(#authClient),
            ),
            returnValueForMissingStub: _FakeGoTrueClient_6(
              this,
              Invocation.getter(#authClient),
            ),
          )
          as _i6.GoTrueClient);

  @override
  bool get allowPasswordReset =>
      (super.noSuchMethod(
            Invocation.getter(#allowPasswordReset),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set allowPasswordReset(bool? value) => super.noSuchMethod(
    Invocation.setter(#allowPasswordReset, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.BehaviorSubject<_i6.User?> watchAuthStateChanges({
    bool? emitLastEvent = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAuthStateChanges, [], {
              #emitLastEvent: emitLastEvent,
            }),
            returnValue: _FakeBehaviorSubject_7<_i6.User?>(
              this,
              Invocation.method(#watchAuthStateChanges, [], {
                #emitLastEvent: emitLastEvent,
              }),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_7<_i6.User?>(
              this,
              Invocation.method(#watchAuthStateChanges, [], {
                #emitLastEvent: emitLastEvent,
              }),
            ),
          )
          as _i7.BehaviorSubject<_i6.User?>);

  @override
  _i13.Future<_i6.AuthResponse> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<_i6.AuthResponse>.value(
              _FakeAuthResponse_8(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.AuthResponse>.value(
              _FakeAuthResponse_8(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i6.AuthResponse>);

  @override
  _i13.Future<_i6.AuthResponse> signInWith({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWith, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<_i6.AuthResponse>.value(
              _FakeAuthResponse_8(
                this,
                Invocation.method(#signInWith, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.AuthResponse>.value(
              _FakeAuthResponse_8(
                this,
                Invocation.method(#signInWith, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i6.AuthResponse>);

  @override
  _i13.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> resetPasswordForEmail({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordForEmail, [], {#email: email}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i6.UserResponse> updateUser({required String? newPassword}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {#newPassword: newPassword}),
            returnValue: _i13.Future<_i6.UserResponse>.value(
              _FakeUserResponse_9(
                this,
                Invocation.method(#updateUser, [], {#newPassword: newPassword}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.UserResponse>.value(
              _FakeUserResponse_9(
                this,
                Invocation.method(#updateUser, [], {#newPassword: newPassword}),
              ),
            ),
          )
          as _i13.Future<_i6.UserResponse>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<bool> onAppStart() =>
      (super.noSuchMethod(
            Invocation.method(#onAppStart, []),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i17.UserRepository {
  @override
  _i2.StudyUApi get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeStudyUApi_0(this, Invocation.getter(#apiClient)),
            returnValueForMissingStub: _FakeStudyUApi_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.StudyUApi);

  @override
  _i3.IAuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeIAuthRepository_1(
              this,
              Invocation.getter(#authRepository),
            ),
            returnValueForMissingStub: _FakeIAuthRepository_1(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i3.IAuthRepository);

  @override
  _i10.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i11.dummyValue<_i10.Ref>(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub: _i11.dummyValue<_i10.Ref>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i10.Ref);

  @override
  _i8.StudyUUser get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeStudyUUser_10(this, Invocation.getter(#user)),
            returnValueForMissingStub: _FakeStudyUUser_10(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i8.StudyUUser);

  @override
  _i13.Future<_i8.StudyUUser> fetchUser() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, []),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(this, Invocation.method(#fetchUser, [])),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(this, Invocation.method(#fetchUser, [])),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  _i13.Future<_i8.StudyUUser> saveUser() =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, []),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(this, Invocation.method(#saveUser, [])),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(this, Invocation.method(#saveUser, [])),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  _i13.Future<_i8.StudyUUser> updatePreferences(
    _i17.PreferenceAction? pinAction,
    String? modelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [pinAction, modelId]),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#updatePreferences, [pinAction, modelId]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#updatePreferences, [pinAction, modelId]),
              ),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  _i13.Future<_i8.StudyUUser> updateLanguage(String? language) =>
      (super.noSuchMethod(
            Invocation.method(#updateLanguage, [language]),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#updateLanguage, [language]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#updateLanguage, [language]),
              ),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  _i13.Future<_i8.StudyUUser> saveCustomPreset(_i15.SavedFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomPreset, [filter]),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#saveCustomPreset, [filter]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#saveCustomPreset, [filter]),
              ),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  _i13.Future<_i8.StudyUUser> deleteCustomPreset(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomPreset, [id]),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#deleteCustomPreset, [id]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#deleteCustomPreset, [id]),
              ),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  List<_i15.SavedFilter> getCustomPresets() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomPresets, []),
            returnValue: <_i15.SavedFilter>[],
            returnValueForMissingStub: <_i15.SavedFilter>[],
          )
          as List<_i15.SavedFilter>);

  @override
  _i13.Future<_i8.StudyUUser> saveActiveFilter({
    required String? page,
    String? presetId,
    _i15.FilterGroup? filterGroup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveActiveFilter, [], {
              #page: page,
              #presetId: presetId,
              #filterGroup: filterGroup,
            }),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#saveActiveFilter, [], {
                  #page: page,
                  #presetId: presetId,
                  #filterGroup: filterGroup,
                }),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#saveActiveFilter, [], {
                  #page: page,
                  #presetId: presetId,
                  #filterGroup: filterGroup,
                }),
              ),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);

  @override
  ({_i15.FilterGroup? filterGroup, String? presetId}) getActiveFilter(
    String? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveFilter, [page]),
            returnValue: (filterGroup: null, presetId: null),
            returnValueForMissingStub: (filterGroup: null, presetId: null),
          )
          as ({_i15.FilterGroup? filterGroup, String? presetId}));

  @override
  ({bool? sortAscending, String? sortColumn}) getActiveSort(String? page) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSort, [page]),
            returnValue: (sortAscending: null, sortColumn: null),
            returnValueForMissingStub: (sortAscending: null, sortColumn: null),
          )
          as ({bool? sortAscending, String? sortColumn}));

  @override
  _i13.Future<_i8.StudyUUser> saveActiveSort({
    required String? page,
    required String? sortColumn,
    required bool? sortAscending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveActiveSort, [], {
              #page: page,
              #sortColumn: sortColumn,
              #sortAscending: sortAscending,
            }),
            returnValue: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#saveActiveSort, [], {
                  #page: page,
                  #sortColumn: sortColumn,
                  #sortAscending: sortAscending,
                }),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.StudyUUser>.value(
              _FakeStudyUUser_10(
                this,
                Invocation.method(#saveActiveSort, [], {
                  #page: page,
                  #sortColumn: sortColumn,
                  #sortAscending: sortAscending,
                }),
              ),
            ),
          )
          as _i13.Future<_i8.StudyUUser>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i6.User {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#aud)),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#aud),
            ),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
