#!/bin/sh

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo 'Local development setup for kitty terminal'
    echo '  Starts the Supabase, Postgres and nginx container compositions in split windows.'
    echo "  Run from the project's root."
    echo ''
    echo 'optional arguments:'
    echo '  -h, --help     show this message and exit'
    exit 0
fi

if [ "$TERM" != "xterm-kitty" ]; then
    echo 'Unsupported terminal.'
    exit 1
fi

cd docker

# Postgres right top
kitty @ launch --cwd=`pwd` --location=vsplit &>/dev/null \
    && kitty @ send-text "cd supabase && docker compose -f docker-compose-db.yml up\n"
# nginx right bottom
kitty @ launch --cwd=`pwd` --location=hsplit &>/dev/null \
    && kitty @ send-text "docker compose -f docker-compose-proxy.yml up\n"
# new tab for development
kitty @ launch --cwd=`pwd`/.. --location=after --type=tab &>/dev/null

# Supabase left
cd supabase
docker compose up
