#!/bin/sh

# Interactively pick a Trello card to work on!
# - create a Github issue
# - create & check out a branch linked to the issue
#
# Requires
# - trello-cli: https://github.com/mheap/trello-cli
# - github-cli: https://cli.github.com
# - fzf: https://github.com/junegunn/fzf
# - zsh or bash

if [ -z "$ZSH_VERSION" -a -z "$BASH_VERSION" ]; then
    echo "Please run $(basename $0) with zsh or bash."
    exit 1
fi

board="Development"
lists=("Core" "App" "Designer")

cards=""
for list in ${lists[@]}; do
    [[ -n "$cards" ]] && cards+=$'\n'
    cards+=$(trello show-cards --board "$board" --list "$list" \
        | tail -n +2 \
        | sed \
            -e '/^[[:space:]]*$/d' \
            -e "s/^\* \([^[:space:]]*\) - /\1:\x1b[2;3m$list → \x1b[0m/")
done

card_id=$(fzf --ansi --delimiter ':' --with-nth '2..' <<<"$cards" \
    | sed 's/:.*//')
