#!/bin/sh

# Interactively pick a Trello card to work on!
# - create a Github issue
# - create & check out a branch linked to the issue
#
# Requires
# - trello-cli: https://github.com/mheap/trello-cli
# - github-cli: https://cli.github.com
# - fzf: https://github.com/junegunn/fzf
# - zsh or bash

if [ -z "$ZSH_VERSION" -a -z "$BASH_VERSION" ]; then
    echo "Please run $(basename $0) with zsh or bash."
    exit 1
fi

function show_boards() {
    trello show-boards \
        | sed -e 's/ (ID: [^)]*)$//' -e '/^[[:space:]]*$/d'
}

function show_lists() {
    trello show-lists --board $1 \
        | tail -n +2 \
        | sed -e 's/ (ID: [^)]*)$//' -e '/^[[:space:]]*$/d'
}

function show_cards() {
    trello show-cards --board $1 --list $2 \
        | tail -n +2 \
        | sed -e 's/^\* [^[:space:]]* //' -e 's/ (ID: [^)]*)$//' -e '/^[[:space:]]*$/d'
}

if [[ -z "$SELFSOURCE" ]]; then
    trello refresh 1>/dev/null || exit 1

    this_file=$(realpath $0)
    board=$(show_boards | fzf \
        --prompt "Select a board: " \
        --preview-window="nohidden" \
        --preview "SELFSOURCE=1 source $this_file && show_lists {}")
    [[ -z "$board" ]] && exit 0

    list=$(show_lists $board | fzf \
        --prompt "Select a list on $board: " \
        --preview-window="nohidden" \
        --preview "SELFSOURCE=1 source $this_file && show_cards $board {}")
    [[ -z "$list" ]] && exit 0

    card=$(show_cards $board $list | fzf \
        --prompt "Select a card on $list: ")
    [[ -z "$card" ]] && exit 0
    echo $card
fi
