// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'body_parts.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BodyParts _$BodyPartsFromJson(Map<String, dynamic> json) => BodyParts(
      headFront: (json['headFront'] as num?)?.toInt() ?? 0,
      headBack: (json['headBack'] as num?)?.toInt() ?? 0,
      neckFront: (json['neckFront'] as num?)?.toInt() ?? 0,
      neckBack: (json['neckBack'] as num?)?.toInt() ?? 0,
      chest: (json['chest'] as num?)?.toInt() ?? 0,
      upperBack: (json['upperBack'] as num?)?.toInt() ?? 0,
      abdomen: (json['abdomen'] as num?)?.toInt() ?? 0,
      lowerBack: (json['lowerBack'] as num?)?.toInt() ?? 0,
      leftShoulder: (json['leftShoulder'] as num?)?.toInt() ?? 0,
      leftUpperArm: (json['leftUpperArm'] as num?)?.toInt() ?? 0,
      leftElbow: (json['leftElbow'] as num?)?.toInt() ?? 0,
      leftLowerArm: (json['leftLowerArm'] as num?)?.toInt() ?? 0,
      leftHand: (json['leftHand'] as num?)?.toInt() ?? 0,
      rightShoulder: (json['rightShoulder'] as num?)?.toInt() ?? 0,
      rightUpperArm: (json['rightUpperArm'] as num?)?.toInt() ?? 0,
      rightElbow: (json['rightElbow'] as num?)?.toInt() ?? 0,
      rightLowerArm: (json['rightLowerArm'] as num?)?.toInt() ?? 0,
      rightHand: (json['rightHand'] as num?)?.toInt() ?? 0,
      pelvis: (json['pelvis'] as num?)?.toInt() ?? 0,
      buttocks: (json['buttocks'] as num?)?.toInt() ?? 0,
      leftUpperLeg: (json['leftUpperLeg'] as num?)?.toInt() ?? 0,
      leftKnee: (json['leftKnee'] as num?)?.toInt() ?? 0,
      leftLowerLeg: (json['leftLowerLeg'] as num?)?.toInt() ?? 0,
      leftFoot: (json['leftFoot'] as num?)?.toInt() ?? 0,
      rightUpperLeg: (json['rightUpperLeg'] as num?)?.toInt() ?? 0,
      rightKnee: (json['rightKnee'] as num?)?.toInt() ?? 0,
      rightLowerLeg: (json['rightLowerLeg'] as num?)?.toInt() ?? 0,
      rightFoot: (json['rightFoot'] as num?)?.toInt() ?? 0,
      vestibular: (json['vestibular'] as num?)?.toInt() ?? 0,
    );

Map<String, dynamic> _$BodyPartsToJson(BodyParts instance) => <String, dynamic>{
      'headFront': instance.headFront,
      'headBack': instance.headBack,
      'neckFront': instance.neckFront,
      'neckBack': instance.neckBack,
      'chest': instance.chest,
      'upperBack': instance.upperBack,
      'abdomen': instance.abdomen,
      'lowerBack': instance.lowerBack,
      'leftShoulder': instance.leftShoulder,
      'leftUpperArm': instance.leftUpperArm,
      'leftElbow': instance.leftElbow,
      'leftLowerArm': instance.leftLowerArm,
      'leftHand': instance.leftHand,
      'rightShoulder': instance.rightShoulder,
      'rightUpperArm': instance.rightUpperArm,
      'rightElbow': instance.rightElbow,
      'rightLowerArm': instance.rightLowerArm,
      'rightHand': instance.rightHand,
      'pelvis': instance.pelvis,
      'buttocks': instance.buttocks,
      'leftUpperLeg': instance.leftUpperLeg,
      'leftKnee': instance.leftKnee,
      'leftLowerLeg': instance.leftLowerLeg,
      'leftFoot': instance.leftFoot,
      'rightUpperLeg': instance.rightUpperLeg,
      'rightKnee': instance.rightKnee,
      'rightLowerLeg': instance.rightLowerLeg,
      'rightFoot': instance.rightFoot,
      'vestibular': instance.vestibular,
    };
