name: All Packages

on:
  push:
    paths:
      - "app/**"
      - "core/**"
      - "designer_v2/**"
      - "flutter_common/**"
      - '*.gitignore'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - ".github/workflows/all_packages.yml"
      - ".github/workflows/init-workspace/**"
  workflow_dispatch:

env:
  MELOS_SDK_PATH: 'auto'

concurrency:
  group: ${{ github.ref }}-all-packages
  cancel-in-progress: true

jobs:
  qualitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Init workspace
        uses: ./.github/workflows/init-workspace

      - name: Generate files
        run: dart run melos generate

      - name: Check generated files
        run: git diff --exit-code

      - name: Run quality check
        run: dart run melos qualitycheck

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Init workspace
        uses: ./.github/workflows/init-workspace

      - name: Run Test
        run: dart run melos test --no-select
