name: App CI using flutter action

on:
  push:
    # paths:
    #     - 'app/*'
    branches:
    - github-action

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Check format
        run: flutter format -l 120 -n . --set-exit-if-changed
        working-directory: ./app
      - name: Lint
        run: flutter analyze
        working-directory: ./app

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Test
        run: flutter test
        working-directory: ./app

  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Enable web support
        run: flutter config --enable-web
      - name: Build web
        run: flutter build web
        working-directory: ./app

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Build android apk
        run: flutter build apk --no-tree-shake-icons
        working-directory: ./app

