name: Check Uncommitted Changes

on:
  push:
    paths:
      - '*.gitignore'
      - 'melos.yaml'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'core/**'
      - 'flutter_common/**'
      - 'app/**'
      - 'designer_v2/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-uncommitted-changes
  cancel-in-progress: true

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Init workspace
        uses: ./.github/workflows/init-workspace
      - name: Generate code
        run: melos run generate
      - name: Check for uncommitted changes
        run: git diff --exit-code
