name: Core CI

on:
  push:
    paths:
        - 'core/**'
    branches:
    - master
    - dev
  pull_request:
    paths:
        - 'core/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
          with:
            channel: beta
      - name: Check format
        working-directory: ./app
        run: |
          flutter format -l 120 -n . > unformatted_files.txt
          cat unformatted_files.txt
          sed -i '/.g.dart/c\' unformatted_files.txt
          cat unformatted_files.txt
          if [ $(wc -l < unformatted_files.txt) -ge 1 ]; then echo 'Please format'; exit 1; fi
      - name: Lint
        run: flutter analyze
        working-directory: ./app
      - name: Check generation of json_serializer
        working-directory: ./app
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          git diff HEAD --exit-code -- "**/*.g.dart"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
          with:
            channel: beta
      - name: Test
        run: flutter test
        working-directory: ./app


