name: Flutter CI

on:
  push:
    branches:
    - master
    - dev
    - github-action

jobs:
  build:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Build apk
        run: flutter build apk
        working-directory: ./app

