name: Linter

on:
  push:

jobs:
    linter:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Check final newline
          uses: johannesvedder/check-final-newline@dev
          with:
            commit_changes: 'true'
            commit_name: 'StudyU Action Bot'
            commit_email: 'noreply@studyu.health'
            commit_message: 'lint: Append newlines to end of files'
