name: Linter

on:
  push:
  workflow_dispatch:

jobs:
    linter:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Check final newline
          uses: johannesvedder/check-final-newline@dev
