name: Linter

on:
  push:

jobs:
    linter:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            token: ${{ secrets.READY_TO_MERGE_TOKEN }}

        - name: Check final newline
          uses: johannesvedder/check-final-newline@main
          with:
            fail_on_missing_newline: 'false'

        - name: Restore ignored files
          run: |
            git checkout -- **/l10n-missing.txt

        - name: Commit changes if any
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: 'lint: Apply final newline changes'
