name: Publish to Pub.dev

# on: push should normally be enough. Using tags is not necessary, since publishing only occurs
# when the version in the pubspec.yml file differs from the pub.dev version. However, additional
# filtering with tags could serve as a second safeguard against accidental version changes and
# thus erroneous publications.
# See: https://github.com/marketplace/actions/dart-and-flutter-package-publisher

on:
  push:
    tags:
      - 'studyu_app-v*'
      - 'studyu_designer-v*'
      - 'studyu_repo_generator-v*'
      - 'studyu_notebook_uploader-v*'
      - 'studyu_core-v*'
      - 'studyu_flutter_common-v*'

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!

      - name: '>> Dart package app <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: app
          dryRunOnly: true # TODO REMOVE IF WORKING

      - name: '>> Dart package designer <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: designer
          dryRunOnly: true # TODO REMOVE IF WORKING

      - name: '>> Dart package repo_generator <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: repo_generator
          dryRunOnly: true # TODO REMOVE IF WORKING

      - name: '>> Dart package notebook_uploader <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: notebook_uploader
          dryRunOnly: true # TODO REMOVE IF WORKING

      - name: '>> Dart package core <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: core
          dryRunOnly: true # TODO REMOVE IF WORKING

      - name: '>> Dart package flutter_common <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: flutter_common
          dryRunOnly: true # TODO REMOVE IF WORKING
