name: Publish to Pub.dev

# on: push should normally be enough. Using tags is not necessary, since publishing only occurs
# when the version in the pubspec.yml file differs from the pub.dev version. However, additional
# filtering with tags could serve as a second safeguard against accidental version changes and
# thus erroneous publications.
# See: https://github.com/marketplace/actions/dart-and-flutter-package-publisher

on:
  push:
    tags:
      - 'studyu_core-v*'
      - 'studyu_flutter_common-v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-publish-pubdev
  cancel-in-progress: true

jobs:
  publishing:
    name: 'Publish to Pub.dev'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: '>> Dart package core <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: core
          # dryRunOnly: true

      - name: '>> Dart package flutter_common <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: flutter_common
          flutter: true
          # dryRunOnly: true
