name: Create release

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Create changelog
    runs-on: ubuntu-latest

    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
