name: Create release

on:
  push:
    branches:
    - create-release
  workflow_dispatch:

jobs:
  changelog:
    name: Create changelog
    runs-on: ubuntu-latest

    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: app/pubspec.yaml
